import { promises as fs } from "node:fs";
import path from "node:path";
import os from "node:os";

const DEFAULT_HOST = "http://127.0.0.1:18789";
const DEFAULT_REQUEST_TIMEOUT_MS = 60_000;

// Lightweight diagnostic logger. Pino isn't available without DI here, so we
// fall back to console with a stable prefix the user can grep:
//   $ tail -f $OTTIE_HOME/daemon.log | grep '\[openclaw\]'
function diag(level: "info" | "warn" | "error", msg: string, fields?: Record<string, unknown>) {
  const line = fields ? `[openclaw] ${msg} ${JSON.stringify(fields)}` : `[openclaw] ${msg}`;
  if (level === "error") console.error(line);
  else if (level === "warn") console.warn(line);
  else console.log(line);
}

/**
 * Resolve the OpenClaw Gateway bearer token. Lookup order:
 *   1. `OPENCLAW_GATEWAY_TOKEN` env var
 *   2. `<HOME>/.openclaw/gateway.token` (auto-generated by `openclaw onboard`)
 *   3. `<HOME>/.openclaw/openclaw.json` `gatewayToken` field
 *   4. null (caller decides whether to require auth)
 *
 * Returns null when nothing is found — some OpenClaw setups run without a
 * token (loopback-trust mode); the caller should still attempt unauthenticated
 * requests and surface a clear error if the gateway rejects them.
 */
export async function resolveOpenclawToken(): Promise<string | null> {
  if (process.env.OPENCLAW_GATEWAY_TOKEN) {
    diag("info", "auth token resolved from OPENCLAW_GATEWAY_TOKEN env var");
    return process.env.OPENCLAW_GATEWAY_TOKEN.trim();
  }
  const home = os.homedir();
  const tokenFile = path.join(home, ".openclaw", "gateway.token");
  try {
    const data = await fs.readFile(tokenFile, "utf8");
    const trimmed = data.trim();
    if (trimmed) {
      diag("info", "auth token resolved from gateway.token file", { path: tokenFile });
      return trimmed;
    }
  } catch (err) {
    diag("info", "no gateway.token file", {
      path: tokenFile,
      reason: err instanceof Error ? err.message : String(err),
    });
  }
  const configFile = path.join(home, ".openclaw", "openclaw.json");
  try {
    const raw = await fs.readFile(configFile, "utf8");
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const candidate =
      (parsed.gatewayToken as string | undefined) ??
      (parsed.gateway_token as string | undefined) ??
      ((parsed.gateway as Record<string, unknown> | undefined)?.token as string | undefined);
    if (typeof candidate === "string" && candidate.trim().length > 0) {
      diag("info", "auth token resolved from openclaw.json", { path: configFile });
      return candidate.trim();
    }
  } catch (err) {
    diag("info", "no openclaw.json or no gatewayToken field", {
      path: configFile,
      reason: err instanceof Error ? err.message : String(err),
    });
  }
  diag("warn", "no auth token found — will try unauthenticated requests");
  return null;
}

interface FetchOptions {
  method: "GET" | "POST";
  path: string;
  body?: unknown;
  host?: string;
  timeoutMs?: number;
}

async function gatewayFetch<T>(opts: FetchOptions): Promise<T> {
  const host = opts.host ?? DEFAULT_HOST;
  const url = `${host.replace(/\/$/, "")}${opts.path}`;
  const token = await resolveOpenclawToken();
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    Accept: "application/json",
  };
  if (token) headers.Authorization = `Bearer ${token}`;

  diag("info", `→ ${opts.method} ${opts.path}`, {
    host,
    hasToken: token !== null,
    bodyBytes: opts.body !== undefined ? JSON.stringify(opts.body).length : 0,
  });

  const startedAt = Date.now();
  const controller = new AbortController();
  const timeoutMs = opts.timeoutMs ?? DEFAULT_REQUEST_TIMEOUT_MS;
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    let response: Response;
    try {
      response = await fetch(url, {
        method: opts.method,
        headers,
        body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,
        signal: controller.signal,
      });
    } catch (err) {
      // Distinguish the common failure shapes so the user knows which to fix:
      //   - AbortError       → timeout (gateway is slow or hung)
      //   - ECONNREFUSED     → gateway not running
      //   - ENOTFOUND/EAI…   → host config issue
      const cause =
        err instanceof Error
          ? `${err.name}: ${err.message}${err.cause ? ` (cause=${String(err.cause)})` : ""}`
          : String(err);
      diag("error", `✕ ${opts.method} ${opts.path} — network error`, {
        url,
        elapsedMs: Date.now() - startedAt,
        timeoutMs,
        cause,
      });
      throw new Error(`OpenClaw network error: ${cause}`);
    }
    const elapsedMs = Date.now() - startedAt;
    if (!response.ok) {
      const text = await response.text().catch(() => "");
      diag("warn", `← ${opts.method} ${opts.path} ${response.status}`, {
        elapsedMs,
        bodyPreview: text.slice(0, 200),
      });
      throw new Error(
        `OpenClaw ${opts.method} ${opts.path} → ${response.status}: ${text.slice(0, 500)}`,
      );
    }
    diag("info", `← ${opts.method} ${opts.path} ${response.status}`, { elapsedMs });
    const contentType = response.headers.get("content-type") ?? "";
    if (contentType.includes("application/json")) {
      return (await response.json()) as T;
    }
    // Some endpoints return plain text. Wrap so the caller still has a typed
    // shape to inspect.
    const text = await response.text();
    return { text } as unknown as T;
  } finally {
    clearTimeout(timer);
  }
}

export interface OpenclawAgent {
  id: string;
  label: string;
  model: string | null;
}

/**
 * Try to enumerate agents. OpenClaw exposes `model: "openclaw/<agentId>"` as
 * the targeting string in OpenAI-compatible mode, so this list doubles as the
 * "model" picker in the UI. The endpoint name varies across versions; we try
 * a couple of common ones and return [] if none work.
 */
export async function listOpenclawAgents(host?: string): Promise<OpenclawAgent[]> {
  const candidates = ["/api/agents", "/api/v1/agents", "/v1/models"];
  for (const candidatePath of candidates) {
    try {
      const result = await gatewayFetch<unknown>({
        method: "GET",
        path: candidatePath,
        host,
        timeoutMs: 5000,
      });
      const parsed = parseAgentList(result);
      if (parsed.length > 0) return parsed;
    } catch {
      // try next
    }
  }
  return [];
}

function parseAgentList(raw: unknown): OpenclawAgent[] {
  if (!raw || typeof raw !== "object") return [];
  const obj = raw as Record<string, unknown>;
  const list = (obj.agents ?? obj.data ?? obj.models ?? raw) as unknown;
  if (!Array.isArray(list)) return [];
  return list
    .map((item): OpenclawAgent | null => {
      if (!item || typeof item !== "object") return null;
      const rec = item as Record<string, unknown>;
      const id = String(rec.id ?? rec.name ?? rec.agentId ?? "").trim();
      if (!id) return null;
      const label = String(rec.label ?? rec.title ?? rec.name ?? id);
      const model =
        typeof rec.model === "string"
          ? rec.model
          : typeof rec.modelId === "string"
            ? rec.modelId
            : null;
      return { id, label, model };
    })
    .filter((agent): agent is OpenclawAgent => agent !== null);
}

export interface OpenclawSendOptions {
  /** The user's message text. */
  text: string;
  /** Optional agent id; OpenClaw routes to default when omitted. */
  agentId?: string;
  /** Optional session id; defaults to "main". */
  sessionId?: string;
  /** Override gateway host (for testing / non-default ports). */
  host?: string;
}

export interface OpenclawSendResult {
  /** Best-effort plain-text reply we can extract from the gateway response. */
  reply: string;
  /** Full raw response, in case the UI wants to render structured data. */
  raw: unknown;
}

/**
 * Send a message to OpenClaw via the inbound-trigger REST endpoint. This is
 * the endpoint that's enabled by default — `/v1/chat/completions` is gated
 * behind a config flag so we don't depend on it.
 *
 * The reply is OpenClaw-formatted — we extract the most likely text field
 * (`text`, `content`, `reply`, `message`) and surface the full payload
 * alongside it so the UI can decide how to render rich responses later.
 */
export async function sendOpenclawMessage(opts: OpenclawSendOptions): Promise<OpenclawSendResult> {
  const sessionId = opts.sessionId ?? "main";
  const body: Record<string, unknown> = { text: opts.text };
  if (opts.agentId) body.agentId = opts.agentId;

  const raw = await gatewayFetch<unknown>({
    method: "POST",
    path: `/api/sessions/${encodeURIComponent(sessionId)}/messages`,
    body,
    host: opts.host,
  });

  return {
    reply: extractReplyText(raw),
    raw,
  };
}

function extractReplyText(raw: unknown): string {
  if (typeof raw === "string") return raw;
  if (!raw || typeof raw !== "object") return "";
  const rec = raw as Record<string, unknown>;
  for (const key of ["reply", "text", "content", "message", "response", "output"]) {
    const value = rec[key];
    if (typeof value === "string" && value.trim()) return value;
  }
  // OpenAI-style: { choices: [{ message: { content } }] }
  const choices = rec.choices;
  if (Array.isArray(choices) && choices[0] && typeof choices[0] === "object") {
    const first = choices[0] as Record<string, unknown>;
    const msg = first.message as Record<string, unknown> | undefined;
    if (msg && typeof msg.content === "string") return msg.content;
  }
  // Fall back to the JSON dump so the user at least sees *something*.
  try {
    return JSON.stringify(raw, null, 2).slice(0, 4000);
  } catch {
    return "";
  }
}
