import { promises as fs } from "node:fs";
import path from "node:path";
import os from "node:os";
import { createPrivateKey, createPublicKey, randomUUID, sign as cryptoSign } from "node:crypto";
import { WebSocket, type RawData } from "ws";

import type { OpenclawAgent } from "./rpc-schemas.js";

const DEFAULT_HOST = "ws://127.0.0.1:18789";
const DEFAULT_REQUEST_TIMEOUT_MS = 60_000;
const DEFAULT_CONNECT_TIMEOUT_MS = 10_000;
const PROTOCOL_VERSION = 3;
// SubjectPublicKeyInfo prefix for an Ed25519 raw public key — the gateway expects
// the 32 raw bytes, base64url-encoded; PEM exports include this 12-byte header.
const ED25519_SPKI_PREFIX = Buffer.from("302a300506032b6570032100", "hex");

function diag(level: "info" | "warn" | "error", msg: string, fields?: Record<string, unknown>) {
  const line = fields ? `[openclaw] ${msg} ${JSON.stringify(fields)}` : `[openclaw] ${msg}`;
  if (level === "error") console.error(line);
  else if (level === "warn") console.warn(line);
  else console.log(line);
}

/**
 * Resolve the OpenClaw Gateway bearer token. Lookup order:
 *   1. `OPENCLAW_GATEWAY_TOKEN` env var
 *   2. `<HOME>/.openclaw/gateway.token` (auto-generated by `openclaw onboard`)
 *   3. `<HOME>/.openclaw/openclaw.json` `gateway.auth.token` field
 *   4. null (caller decides whether to require auth)
 */
export async function resolveOpenclawToken(): Promise<string | null> {
  if (process.env.OPENCLAW_GATEWAY_TOKEN) {
    diag("info", "auth token resolved from OPENCLAW_GATEWAY_TOKEN env var");
    return process.env.OPENCLAW_GATEWAY_TOKEN.trim();
  }
  const home = os.homedir();
  const tokenFile = path.join(home, ".openclaw", "gateway.token");
  try {
    const data = await fs.readFile(tokenFile, "utf8");
    const trimmed = data.trim();
    if (trimmed) {
      diag("info", "auth token resolved from gateway.token file", { path: tokenFile });
      return trimmed;
    }
  } catch (err) {
    diag("info", "no gateway.token file", {
      path: tokenFile,
      reason: err instanceof Error ? err.message : String(err),
    });
  }
  const configFile = path.join(home, ".openclaw", "openclaw.json");
  try {
    const raw = await fs.readFile(configFile, "utf8");
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const gateway = parsed.gateway as Record<string, unknown> | undefined;
    const auth = gateway?.auth as Record<string, unknown> | undefined;
    const candidate =
      (parsed.gatewayToken as string | undefined) ??
      (parsed.gateway_token as string | undefined) ??
      (gateway?.token as string | undefined) ??
      (auth?.token as string | undefined);
    if (typeof candidate === "string" && candidate.trim().length > 0) {
      diag("info", "auth token resolved from openclaw.json", { path: configFile });
      return candidate.trim();
    }
  } catch (err) {
    diag("info", "no openclaw.json or no gatewayToken field", {
      path: configFile,
      reason: err instanceof Error ? err.message : String(err),
    });
  }
  diag("warn", "no auth token found — will try unauthenticated requests");
  return null;
}

interface DeviceIdentity {
  deviceId: string;
  privateKeyPem: string;
  publicKeyPem: string;
}

/**
 * Read the OpenClaw device identity that the local CLI uses. Same-machine
 * Ottie reuses this so the gateway's `paired.json` already trusts us — no
 * separate pairing flow needed.
 */
async function loadDeviceIdentity(): Promise<DeviceIdentity | null> {
  const file = path.join(os.homedir(), ".openclaw", "identity", "device.json");
  try {
    const raw = await fs.readFile(file, "utf8");
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    if (
      typeof parsed.deviceId === "string" &&
      typeof parsed.privateKeyPem === "string" &&
      typeof parsed.publicKeyPem === "string"
    ) {
      return {
        deviceId: parsed.deviceId,
        privateKeyPem: parsed.privateKeyPem,
        publicKeyPem: parsed.publicKeyPem,
      };
    }
    diag("warn", "device.json missing required fields", { path: file });
    return null;
  } catch (err) {
    diag("warn", "no device.json (run `openclaw onboard` first)", {
      path: file,
      reason: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
}

function base64UrlEncode(buf: Buffer): string {
  return buf.toString("base64").replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/g, "");
}

function publicKeyRawBase64UrlFromPem(publicKeyPem: string): string {
  const der = createPublicKey(publicKeyPem).export({ type: "spki", format: "der" });
  const buf = Buffer.from(der);
  if (
    buf.length === ED25519_SPKI_PREFIX.length + 32 &&
    buf.subarray(0, ED25519_SPKI_PREFIX.length).equals(ED25519_SPKI_PREFIX)
  ) {
    return base64UrlEncode(buf.subarray(ED25519_SPKI_PREFIX.length));
  }
  return base64UrlEncode(buf);
}

function signEd25519(privateKeyPem: string, payload: string): string {
  const key = createPrivateKey(privateKeyPem);
  return base64UrlEncode(cryptoSign(null, Buffer.from(payload, "utf8"), key));
}

function normalizeMetadata(value: string | null | undefined): string {
  if (typeof value !== "string") return "";
  const trimmed = value.trim();
  if (!trimmed) return "";
  return trimmed.replace(/[A-Z]/g, (c) => String.fromCharCode(c.charCodeAt(0) + 32));
}

function buildDeviceAuthPayloadV3(p: {
  deviceId: string;
  clientId: string;
  clientMode: string;
  role: string;
  scopes: string[];
  signedAtMs: number;
  token: string | null;
  nonce: string;
  platform: string;
  deviceFamily?: string | null;
}): string {
  return [
    "v3",
    p.deviceId,
    p.clientId,
    p.clientMode,
    p.role,
    p.scopes.join(","),
    String(p.signedAtMs),
    p.token ?? "",
    p.nonce,
    normalizeMetadata(p.platform),
    normalizeMetadata(p.deviceFamily),
  ].join("|");
}

function normalizeOperatorScopes(input: string[]): string[] {
  const set = new Set<string>();
  for (const s of input) {
    const t = s.trim();
    if (t) set.add(t);
  }
  if (set.has("operator.admin")) {
    set.add("operator.read");
    set.add("operator.write");
  } else if (set.has("operator.write")) {
    set.add("operator.read");
  }
  return [...set].sort();
}

function normalizeWsUrl(host: string): string {
  const trimmed = host.replace(/\/$/, "");
  if (trimmed.startsWith("ws://") || trimmed.startsWith("wss://")) return trimmed;
  if (trimmed.startsWith("http://")) return "ws://" + trimmed.slice("http://".length);
  if (trimmed.startsWith("https://")) return "wss://" + trimmed.slice("https://".length);
  return trimmed;
}

interface PendingRequest {
  method: string;
  expectFinal: boolean;
  resolve: (payload: unknown) => void;
  reject: (err: Error) => void;
  timer: NodeJS.Timeout;
}

interface RpcFrame {
  type: string;
  id?: string;
  ok?: boolean;
  event?: string;
  payload?: unknown;
  error?: { code?: string; message?: string; details?: unknown };
}

/**
 * Minimal OpenClaw gateway client. One connection per call site is fine for
 * Ottie's traffic shape (chat is low-frequency, agent listing is rare).
 */
class GatewayConn {
  private ws: WebSocket | null = null;
  private readonly pending = new Map<string, PendingRequest>();
  private opened = false;
  private closed = false;

  constructor(
    private readonly opts: {
      host: string;
      token: string | null;
      identity: DeviceIdentity;
      connectTimeoutMs: number;
    },
  ) {}

  open(): Promise<void> {
    return new Promise((resolveOpen, rejectOpen) => {
      const url = normalizeWsUrl(this.opts.host) + "/";
      const ws = new WebSocket(url);
      this.ws = ws;
      let connectId: string | null = null;
      let settled = false;
      const fail = (err: Error) => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        try {
          ws.terminate();
        } catch {
          /* noop */
        }
        this.failPending(err);
        rejectOpen(err);
      };
      const timer = setTimeout(
        () => fail(new Error(`OpenClaw connect timeout after ${this.opts.connectTimeoutMs}ms`)),
        this.opts.connectTimeoutMs,
      );

      ws.on("error", (err) => fail(err instanceof Error ? err : new Error(String(err))));
      ws.on("close", (code, reasonBuf) => {
        const reason = reasonBuf?.toString() || "";
        const err = new Error(`OpenClaw WS closed (${code}${reason ? `: ${reason}` : ""})`);
        if (!settled) fail(err);
        else if (!this.closed) this.failPending(err);
      });

      const onPreHelloMessage = (data: RawData) => {
        let frame: RpcFrame;
        try {
          frame = JSON.parse(data.toString()) as RpcFrame;
        } catch {
          return;
        }

        if (frame.type === "event" && frame.event === "connect.challenge") {
          const nonce = (frame.payload as { nonce?: string } | undefined)?.nonce;
          if (typeof nonce !== "string") {
            fail(new Error("OpenClaw connect.challenge missing nonce"));
            return;
          }
          try {
            connectId = randomUUID();
            ws.send(JSON.stringify(this.buildConnectFrame(connectId, nonce)));
          } catch (err) {
            fail(err instanceof Error ? err : new Error(String(err)));
          }
          return;
        }

        if (frame.type === "res" && frame.id === connectId) {
          if (!frame.ok) {
            const msg = frame.error?.message ?? JSON.stringify(frame.error ?? frame.payload);
            fail(new Error(`OpenClaw connect rejected: ${msg}`));
            return;
          }
          settled = true;
          clearTimeout(timer);
          ws.off("message", onPreHelloMessage);
          ws.on("message", (d) => this.onMessage(d));
          this.opened = true;
          diag("info", "gateway connected", { host: this.opts.host });
          resolveOpen();
          return;
        }
        // Other pre-hello frames (e.g. early health events) are ignored.
      };
      ws.on("message", onPreHelloMessage);
    });
  }

  private buildConnectFrame(id: string, nonce: string): unknown {
    const role = "operator";
    const scopes = normalizeOperatorScopes(["operator.admin"]);
    const signedAtMs = Date.now();
    const platform = process.platform;
    const clientId = "gateway-client";
    const clientMode = "backend";
    const payload = buildDeviceAuthPayloadV3({
      deviceId: this.opts.identity.deviceId,
      clientId,
      clientMode,
      role,
      scopes,
      signedAtMs,
      token: this.opts.token,
      nonce,
      platform,
    });
    const signature = signEd25519(this.opts.identity.privateKeyPem, payload);
    const publicKey = publicKeyRawBase64UrlFromPem(this.opts.identity.publicKeyPem);

    const params: Record<string, unknown> = {
      minProtocol: PROTOCOL_VERSION,
      maxProtocol: PROTOCOL_VERSION,
      client: {
        id: clientId,
        version: "ottie",
        platform,
        mode: clientMode,
        instanceId: randomUUID(),
      },
      caps: [],
      role,
      scopes,
      device: {
        id: this.opts.identity.deviceId,
        publicKey,
        signature,
        signedAt: signedAtMs,
        nonce,
      },
    };
    if (this.opts.token) params.auth = { token: this.opts.token };
    return { type: "req", id, method: "connect", params };
  }

  private onMessage(data: RawData): void {
    let frame: RpcFrame;
    try {
      frame = JSON.parse(data.toString()) as RpcFrame;
    } catch {
      return;
    }
    if (frame.type === "event") return; // Stream events are not surfaced.
    if (frame.type !== "res" || typeof frame.id !== "string") return;

    const p = this.pending.get(frame.id);
    if (!p) return;
    if (!frame.ok) {
      this.pending.delete(frame.id);
      clearTimeout(p.timer);
      const msg = frame.error?.message ?? JSON.stringify(frame.error ?? frame.payload);
      p.reject(new Error(`OpenClaw RPC ${p.method} failed: ${msg}`));
      return;
    }
    if (p.expectFinal) {
      const status = (frame.payload as { status?: unknown } | undefined)?.status;
      // The first 'res' for streaming methods carries status:"accepted"; the
      // final one carries status:"ok" with the result. Anything else is final.
      if (status === "accepted") return;
    }
    this.pending.delete(frame.id);
    clearTimeout(p.timer);
    p.resolve(frame.payload);
  }

  request<T>(
    method: string,
    params: unknown,
    opts: { expectFinal?: boolean; timeoutMs?: number } = {},
  ): Promise<T> {
    if (!this.opened || !this.ws || this.ws.readyState !== WebSocket.OPEN) {
      return Promise.reject(new Error("OpenClaw gateway not connected"));
    }
    const id = randomUUID();
    const timeoutMs = opts.timeoutMs ?? DEFAULT_REQUEST_TIMEOUT_MS;
    return new Promise<T>((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`OpenClaw RPC ${method} timeout after ${timeoutMs}ms`));
      }, timeoutMs);
      this.pending.set(id, {
        method,
        expectFinal: opts.expectFinal !== false,
        resolve: (v) => resolve(v as T),
        reject,
        timer,
      });
      this.ws!.send(JSON.stringify({ type: "req", id, method, params }));
    });
  }

  close(): void {
    if (this.closed) return;
    this.closed = true;
    try {
      this.ws?.close();
    } catch {
      /* noop */
    }
    this.ws = null;
  }

  private failPending(err: Error): void {
    for (const [id, p] of this.pending) {
      clearTimeout(p.timer);
      p.reject(err);
      this.pending.delete(id);
    }
  }
}

async function withGateway<T>(
  host: string | undefined,
  fn: (conn: GatewayConn) => Promise<T>,
): Promise<T> {
  const identity = await loadDeviceIdentity();
  if (!identity) {
    throw new Error(
      "OpenClaw device identity not found at ~/.openclaw/identity/device.json. " +
        "Run `openclaw onboard` on this machine first.",
    );
  }
  const token = await resolveOpenclawToken();
  const conn = new GatewayConn({
    host: host ?? DEFAULT_HOST,
    token,
    identity,
    connectTimeoutMs: DEFAULT_CONNECT_TIMEOUT_MS,
  });
  try {
    await conn.open();
    return await fn(conn);
  } finally {
    conn.close();
  }
}

/**
 * Enumerate agents registered with OpenClaw. The gateway's `agents.list`
 * RPC returns `{defaultId, agents: [{id, model: {primary}, ...}]}`.
 */
export async function listOpenclawAgents(host?: string): Promise<OpenclawAgent[]> {
  return withGateway(host, async (conn) => {
    const raw = await conn.request<unknown>(
      "agents.list",
      {},
      {
        expectFinal: false,
        timeoutMs: 5_000,
      },
    );
    return parseAgentList(raw);
  });
}

function parseAgentList(raw: unknown): OpenclawAgent[] {
  if (!raw || typeof raw !== "object") return [];
  const list = (raw as Record<string, unknown>).agents;
  if (!Array.isArray(list)) return [];
  return list
    .map((item): OpenclawAgent | null => {
      if (!item || typeof item !== "object") return null;
      const rec = item as Record<string, unknown>;
      const id = String(rec.id ?? "").trim();
      if (!id) return null;
      const model = extractAgentModel(rec.model);
      return { id, label: id, model };
    })
    .filter((a): a is OpenclawAgent => a !== null);
}

function extractAgentModel(value: unknown): string | null {
  if (typeof value === "string" && value.trim()) return value;
  if (value && typeof value === "object") {
    const rec = value as Record<string, unknown>;
    const primary = rec.primary;
    if (typeof primary === "string" && primary.trim()) return primary;
  }
  return null;
}

export interface OpenclawSendOptions {
  /** The user's message text. */
  text: string;
  /** Optional agent id; OpenClaw routes to default when omitted. */
  agentId?: string;
  /** Optional session id; defaults to "main". */
  sessionId?: string;
  /** Override gateway URL (ws:// or http://; both normalized). */
  host?: string;
}

export interface OpenclawSendResult {
  /** Best-effort plain-text reply extracted from the gateway response. */
  reply: string;
  /** Full raw response, in case the UI wants to render structured data. */
  raw: unknown;
}

/**
 * Send a message via the gateway's `agent` RPC. The first response carries
 * `status:"accepted"`; we wait for the final response with the run result.
 */
export async function sendOpenclawMessage(opts: OpenclawSendOptions): Promise<OpenclawSendResult> {
  return withGateway(opts.host, async (conn) => {
    const params: Record<string, unknown> = {
      message: opts.text,
      sessionId: opts.sessionId ?? "main",
      idempotencyKey: randomUUID(),
    };
    if (opts.agentId) params.agentId = opts.agentId;

    const raw = await conn.request<unknown>("agent", params, {
      expectFinal: true,
      timeoutMs: DEFAULT_REQUEST_TIMEOUT_MS,
    });
    return { reply: extractReplyText(raw), raw };
  });
}

function textFromAgentPayloads(rec: Record<string, unknown>): string | null {
  const result = rec.result;
  if (!result || typeof result !== "object") return null;
  const payloads = (result as Record<string, unknown>).payloads;
  if (!Array.isArray(payloads)) return null;
  const texts = payloads.flatMap((item) => {
    if (!item || typeof item !== "object") return [];
    const t = (item as Record<string, unknown>).text;
    return typeof t === "string" && t.trim() ? [t] : [];
  });
  return texts.length > 0 ? texts.join("\n\n") : null;
}

function textFromFlatFields(rec: Record<string, unknown>): string | null {
  for (const key of ["reply", "text", "content", "message", "response", "output"]) {
    const value = rec[key];
    if (typeof value === "string" && value.trim()) return value;
  }
  return null;
}

function textFromOpenAiChoices(rec: Record<string, unknown>): string | null {
  const choices = rec.choices;
  if (!Array.isArray(choices) || !choices[0] || typeof choices[0] !== "object") return null;
  const msg = (choices[0] as Record<string, unknown>).message as
    | Record<string, unknown>
    | undefined;
  return msg && typeof msg.content === "string" ? msg.content : null;
}

function extractReplyText(raw: unknown): string {
  if (typeof raw === "string") return raw;
  if (!raw || typeof raw !== "object") return "";
  const rec = raw as Record<string, unknown>;
  const fromAgent = textFromAgentPayloads(rec);
  if (fromAgent !== null) return fromAgent;
  const fromFlat = textFromFlatFields(rec);
  if (fromFlat !== null) return fromFlat;
  const fromChoices = textFromOpenAiChoices(rec);
  if (fromChoices !== null) return fromChoices;
  try {
    return JSON.stringify(raw, null, 2).slice(0, 4000);
  } catch {
    return "";
  }
}
