// Plugin catalog — the curated list of plugins the Extensions store offers.
//
// Each entry carries everything needed for one-click install:
//   - The daemon-side bridge (JS source written into ~/.ottie/plugins/<id>/)
//   - Optional companion app metadata (a separate native app the bridge talks
//     to; e.g. the CodeIsland macOS app that displays a Dynamic Island panel
//     above every window)
//
// Today the catalog is hardcoded so we can ship the codeisland integration
// without standing up a registry server. A future revision can swap this for
// a fetched manifest while keeping the same shape.

export type PluginPlatform = "darwin" | "win32" | "linux";

export interface PluginCompanionApp {
  /** macOS bundle name used for `open -a <name>` and `pgrep`. */
  bundleName: string;
  /** Suggested install location for the .app on disk (macOS only). */
  preferredInstallPath: string;
  /**
   * GitHub `owner/repo` to fetch the latest `.dmg` / `.zip` asset from.
   * When set, install will try to download + place the .app automatically.
   * If unset (or download fails) the UI falls back to opening
   * `releaseBrowserUrl` so the user can grab the binary manually.
   */
  githubReleasesRepo?: string;
  /** User-facing release page (fallback for manual install). */
  releaseBrowserUrl: string;
  /** Heuristic file extension preference for the auto-download asset. */
  assetExtensions: readonly string[];
}

export interface PluginCatalogEntry {
  id: string;
  name: string;
  description: string;
  author: string;
  /** Platforms this plugin is meaningful on. Hidden in the UI elsewhere. */
  platforms: readonly PluginPlatform[];
  /** Daemon-side bridge module: gets written verbatim into index.js. */
  bridgeSource: string;
  /** Companion native app the bridge talks to (optional). */
  companionApp?: PluginCompanionApp;
}

const CODEISLAND_BRIDGE_SOURCE = `\
// Auto-generated by Ottie plugin installer. Do not edit by hand.
// Source of truth: packages/server/src/server/plugins/plugin-catalog.ts
import net from "node:net";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";

const SOCKET_PATH = path.join(os.tmpdir(), "codeisland.sock");

async function sendToCodeIsland(message) {
  try {
    await fs.access(SOCKET_PATH);
  } catch {
    return;
  }
  await new Promise((resolve) => {
    const client = net.createConnection(SOCKET_PATH);
    client.on("error", () => resolve());
    client.on("connect", () => {
      client.write(JSON.stringify(message) + "\\n");
      client.end();
      resolve();
    });
  });
}

export function activate(api) {
  api.logger.info({ socket: SOCKET_PATH }, "CodeIsland plugin activated");
  api.events.on("message", (msg) => {
    if (!msg || typeof msg !== "object") return;
    if (msg.type === "agent_stream") {
      void sendToCodeIsland({
        type: "stream",
        agentId: msg.payload?.agentId,
        delta: msg.payload?.delta,
      });
    } else if (msg.type === "agent_update") {
      void sendToCodeIsland({
        type: "update",
        agentId: msg.payload?.agentId,
        status: msg.payload?.status,
      });
    }
  });
}

export function deactivate() {
  // Nothing to clean up — connections are short-lived per-message.
}
`;

export const BUILTIN_PLUGIN_CATALOG: readonly PluginCatalogEntry[] = [
  {
    id: "codeisland",
    name: "CodeIsland Notch Integration",
    description:
      "A real-time macOS Dynamic Island panel for your AI coding agents. See tool calls and stream status without switching windows.",
    author: "wxtsky",
    platforms: ["darwin"],
    bridgeSource: CODEISLAND_BRIDGE_SOURCE,
    companionApp: {
      bundleName: "CodeIsland",
      preferredInstallPath: "/Applications/CodeIsland.app",
      githubReleasesRepo: "wxtsky/CodeIsland",
      releaseBrowserUrl: "https://github.com/wxtsky/CodeIsland/releases/latest",
      assetExtensions: [".dmg", ".zip"],
    },
  },
];

// Mutable snapshot used by the running daemon. Built-in entries always live
// here; remote catalog entries are merged via `setRemoteCatalogEntries`.
let runtimeCatalog: readonly PluginCatalogEntry[] = BUILTIN_PLUGIN_CATALOG;

export function getCatalog(): readonly PluginCatalogEntry[] {
  return runtimeCatalog;
}

/**
 * Merge remote-fetched, signature-verified entries with the built-ins. A
 * built-in entry with the same id is kept (the daemon ships with the
 * authoritative copy); we only add entries that aren't shadowed.
 */
export function setRemoteCatalogEntries(entries: readonly PluginCatalogEntry[]): void {
  const builtinIds = new Set(BUILTIN_PLUGIN_CATALOG.map((e) => e.id));
  const additions = entries.filter((e) => !builtinIds.has(e.id));
  runtimeCatalog = [...BUILTIN_PLUGIN_CATALOG, ...additions];
}

export function findCatalogEntry(id: string): PluginCatalogEntry | undefined {
  return runtimeCatalog.find((entry) => entry.id === id);
}
