import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import type pino from "pino";

import { z } from "zod";

import {
  AiShareInviteEnvelopeSchema,
  AiShareTimelineEntrySchema,
  type AiShareInviteEnvelope,
} from "./ai-share-types.js";

/**
 * Phase 4 v2/e — auditable transcript of every ai-share session,
 * append-only JSONL, one file per inviteId per side.
 *
 * The on-disk transcript is the canonical post-mortem record: every
 * signed envelope this side observed (sent or received), plus
 * timestamps. Both sides keep their own copy because (a) JSONL
 * append-only writes are simple + crash-safe and (b) §7 promises an
 * "auditable transcript" — Bob can review what happened on his
 * filesystem without trusting Alice's daemon to surface it.
 *
 * Storage layout:
 *
 *   $OTTIE_HOME/ai-shares/{inviteId}.jsonl
 *
 * First line is always a `header` record carrying the side (outbound
 * vs inbound) + the verified invite envelope. Subsequent lines are
 * one event per accept / decline / end / prompt / timeline. v3 may
 * add a separate index file if scan-all-invites grows expensive.
 *
 * The redaction rule from v2/d (§7 "Bob does not see") still applies:
 * the friend's transcript only carries the redacted timeline entries
 * the owner actually shipped — tool calls etc. were never written
 * here in the first place because they were never on the wire.
 */

const TRANSCRIPT_DIRNAME = "ai-shares";

export const AiShareTranscriptHeaderSchema = z.object({
  v: z.literal(1),
  kind: z.literal("header"),
  inviteId: z.string().min(1),
  side: z.enum(["outbound", "inbound"]),
  invite: AiShareInviteEnvelopeSchema,
  /** ISO timestamp when this daemon opened the transcript. */
  createdAt: z.string(),
});
export type AiShareTranscriptHeader = z.infer<typeof AiShareTranscriptHeaderSchema>;

export const AiShareTranscriptAcceptSchema = z.object({
  v: z.literal(1),
  kind: z.literal("accept"),
  /** "self" if this daemon emitted the accept; "peer" otherwise. */
  origin: z.enum(["self", "peer"]),
  acceptedAt: z.string(),
  signatureB64: z.string(),
});

export const AiShareTranscriptDeclineSchema = z.object({
  v: z.literal(1),
  kind: z.literal("decline"),
  origin: z.enum(["self", "peer"]),
  declinedAt: z.string(),
  reason: z.string().optional(),
  signatureB64: z.string(),
});

export const AiShareTranscriptEndSchema = z.object({
  v: z.literal(1),
  kind: z.literal("end"),
  origin: z.enum(["self", "peer"]),
  endedAt: z.string(),
  reason: z.string().optional(),
  signatureB64: z.string(),
});

export const AiShareTranscriptPromptSchema = z.object({
  v: z.literal(1),
  kind: z.literal("prompt"),
  /** "sent" = this side emitted the prompt; "received" = peer's prompt. */
  origin: z.enum(["sent", "received"]),
  promptId: z.string(),
  sentAt: z.string(),
  body: z.string(),
  signatureB64: z.string(),
});

export const AiShareTranscriptTimelineSchema = z.object({
  v: z.literal(1),
  kind: z.literal("timeline"),
  origin: z.enum(["sent", "received"]),
  eventId: z.string(),
  sentAt: z.string(),
  entry: AiShareTimelineEntrySchema,
  signatureB64: z.string(),
});

export const AiShareTranscriptLineSchema = z.discriminatedUnion("kind", [
  AiShareTranscriptHeaderSchema,
  AiShareTranscriptAcceptSchema,
  AiShareTranscriptDeclineSchema,
  AiShareTranscriptEndSchema,
  AiShareTranscriptPromptSchema,
  AiShareTranscriptTimelineSchema,
]);
export type AiShareTranscriptLine = z.infer<typeof AiShareTranscriptLineSchema>;

export function aiShareTranscriptDirPath(ottieHome: string): string {
  return path.join(ottieHome, TRANSCRIPT_DIRNAME);
}

function isSafeInviteId(inviteId: string): boolean {
  // Defensive: no path traversal, no control chars. inviteId is
  // generated by daemons (`ais_…`), but this file path is derived
  // from network input ultimately, so it must be safe even if a
  // malformed envelope made it past the schema.
  return /^[A-Za-z0-9_-]{1,64}$/.test(inviteId);
}

export function aiShareTranscriptFilePath(ottieHome: string, inviteId: string): string | null {
  if (!isSafeInviteId(inviteId)) return null;
  return path.join(aiShareTranscriptDirPath(ottieHome), `${inviteId}.jsonl`);
}

export class AiShareTranscriptStore {
  private readonly ottieHome: string;
  private readonly logger: pino.Logger | undefined;
  /** Per-invite cached header so re-opens don't re-stat / re-read. */
  private readonly openedInvites = new Set<string>();

  constructor(options: { ottieHome: string; logger?: pino.Logger }) {
    this.ottieHome = options.ottieHome;
    this.logger = options.logger?.child({ module: "ai-share-transcript" });
  }

  /**
   * Open (or no-op-reopen) a transcript: ensures the parent dir
   * exists, writes the header line if the file is fresh, and stamps
   * `createdAt` from the system clock. Idempotent — calling this
   * on an existing transcript leaves the prior header alone.
   */
  open(input: {
    inviteId: string;
    side: "outbound" | "inbound";
    invite: AiShareInviteEnvelope;
  }): void {
    const filePath = aiShareTranscriptFilePath(this.ottieHome, input.inviteId);
    if (!filePath) {
      this.logger?.warn({ inviteId: input.inviteId }, "ai_share_transcript_unsafe_invite_id");
      return;
    }
    try {
      mkdirSync(aiShareTranscriptDirPath(this.ottieHome), { recursive: true });
    } catch (err) {
      this.logger?.warn({ err }, "ai_share_transcript_mkdir_failed");
      return;
    }
    if (existsSync(filePath)) {
      this.openedInvites.add(input.inviteId);
      return;
    }
    const header: AiShareTranscriptHeader = {
      v: 1,
      kind: "header",
      inviteId: input.inviteId,
      side: input.side,
      invite: input.invite,
      createdAt: new Date().toISOString(),
    };
    try {
      appendFileSync(filePath, JSON.stringify(header) + "\n", { encoding: "utf8" });
      this.openedInvites.add(input.inviteId);
      this.logger?.info(
        { inviteId: input.inviteId, side: input.side },
        "ai_share_transcript_opened",
      );
    } catch (err) {
      this.logger?.warn({ err, inviteId: input.inviteId }, "ai_share_transcript_open_failed");
    }
  }

  append(input: { inviteId: string; line: AiShareTranscriptLine }): void {
    const filePath = aiShareTranscriptFilePath(this.ottieHome, input.inviteId);
    if (!filePath) return;
    try {
      appendFileSync(filePath, JSON.stringify(input.line) + "\n", { encoding: "utf8" });
    } catch (err) {
      this.logger?.warn(
        { err, inviteId: input.inviteId, kind: input.line.kind },
        "ai_share_transcript_append_failed",
      );
    }
  }

  /** Read all transcript lines for `inviteId`. Empty array if missing or unparseable. */
  read(inviteId: string): AiShareTranscriptLine[] {
    const filePath = aiShareTranscriptFilePath(this.ottieHome, inviteId);
    if (!filePath || !existsSync(filePath)) return [];
    let raw: string;
    try {
      raw = readFileSync(filePath, "utf8");
    } catch (err) {
      this.logger?.warn({ err, inviteId }, "ai_share_transcript_read_failed");
      return [];
    }
    const lines: AiShareTranscriptLine[] = [];
    for (const line of raw.split("\n")) {
      if (line.length === 0) continue;
      try {
        const parsed = AiShareTranscriptLineSchema.safeParse(JSON.parse(line));
        if (parsed.success) lines.push(parsed.data);
      } catch (err) {
        this.logger?.warn({ err, inviteId }, "ai_share_transcript_line_unparseable");
      }
    }
    return lines;
  }

  /** List inviteIds with a transcript on disk. Used by the v3 history UI. */
  listInviteIds(): string[] {
    const dir = aiShareTranscriptDirPath(this.ottieHome);
    if (!existsSync(dir)) return [];
    let names: string[];
    try {
      names = readdirSync(dir);
    } catch (err) {
      this.logger?.warn({ err }, "ai_share_transcript_list_failed");
      return [];
    }
    return names
      .filter((n) => n.endsWith(".jsonl"))
      .map((n) => n.slice(0, -".jsonl".length))
      .filter(isSafeInviteId);
  }
}
